version: '3.3'

services:
  aurad:
    container_name: aurad_erascope
    image: auranw/local-aurad:latest
    ports:
      - '1317:1317'
      - '26656:26656'
      - '26657:26657'
      - '9090:9090'
