version: '3.3'

services:
  psql:
    container_name: psql_erascope
    build: ./docker/psql/
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_DB_TEST: ${POSTGRES_DB_TEST}
    networks:
      - dev_network
  redis:
    image: redis:latest
    container_name: redis_erascope
    ports:
      - '6379:6379'
    networks:
      - dev_network
networks:
  dev_network:

volumes:
  data:
