name: CI test

on:
  workflow_dispatch:
  push:
    branches-ignore: [main, develop, serenity, euphoria, feat/cicd]

jobs:
  lint:
    uses: ./.github/workflows/lint.yml
  test:
    uses: ./.github/workflows/test.yml
    secrets: inherit