name: Build

on:
  workflow_dispatch:
  push:
    branches: [main, develop, serenity, euphoria]

jobs:
  lint:
    uses: ./.github/workflows/lint.yml
  test:
    uses: ./.github/workflows/test.yml
    secrets: inherit

  build:
    needs: [test, lint]
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v3
      - name: Set environment variable
        run: |
          SHORT_SHA_COMMIT=$(git rev-parse --short HEAD)
          echo CONTAINER_RELEASE_IMAGE=ghcr.io/aura-nw/horoscope-v2:${GITHUB_REF_NAME}_${SHORT_SHA_COMMIT} >> $GITHUB_ENV
          echo REPO_MANIFEST_NAME=gitops >> $GITHUB_ENV
          echo REPO_MANIFEST_URL=github.com/aura-nw/gitops.git >> $GITHUB_ENV
          echo REPO_MANIFEST_BRANCH=main >> $GITHUB_ENV
          echo REPO_MANIFEST_ENV_DEV=./clusters/k8s-dev/horoscope-v2 >> $GITHUB_ENV
          echo REPO_MANIFEST_ENV_STAGING=./clusters/k8s-prod/horoscope-v2 >> $GITHUB_ENV
          echo REPO_MANIFEST_ENV_MAIN=./clusters/k8s-main/horoscope-v2 >> $GITHUB_ENV
          echo REPO_MANIFEST_ENV_EUPHORIA=./clusters/k8s-testnet-euphoria/horoscope-v2 >> $GITHUB_ENV
          echo REPO_MANIFEST_ENV_SERENITY=./clusters/k8s-testnet-serenity/horoscope-v2 >> $GITHUB_ENV
          echo REPO_MANIFEST_TAG_IMAGE=image_horoscope-v2 >> $GITHUB_ENV
      - name: setup git config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
      - name: Build the Docker image and push it to the registry
        env:
          GITHUB_USERNAME: ${{ github.actor }}
          GITHUB_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
        run: |
          chmod 777 -R ./ci
          ./ci/build.sh
      - name: Update manifest
        env:
          PERSONAL_ACCESS_TOKEN: ${{ secrets.REGISTRY_PASSWORD }}
        run: |
          ./ci/updateManifest.sh
