name: CI Test

on:
  workflow_dispatch:
  push:
    branches: [main, develop, serenity, euphoria, feat/cicd]

jobs:
  lint:
    uses: ./.github/workflows/lint.yml
  test:
    uses: ./.github/workflows/test.yml
    secrets: inherit