name: Lint

on:
  pull_request:
  workflow_call:

jobs:
  lint:
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.14
          registry-url: https://npm.pkg.github.com/aura-nw
      # - name: Install Yarn
      #   run: npm install -g yarn

      - name: Cache node modules
        id: cache-npm
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - if: ${{ steps.cache-npm.outputs.cache-hit != 'true' }}
        name: List the state of node modules
        continue-on-error: true
        run: yarn list
      - name: Setup .yarnrc.yml
        run: |
          yarn -v
          yarn config set npmScopes.aura-nw.npmRegistryServer "https://npm.pkg.github.com"
          yarn config set npmScopes.aura-nw.npmAlwaysAuth true
          yarn config set npmScopes.aura-nw.npmAuthToken $NPM_AUTH_TOKEN
        env:
          NPM_AUTH_TOKEN: ${{ secrets.KEY_NPM_RC }}
      - name: Install dependencies
        run: yarn install --immutable
      - name: Lint check
        run: yarn lint
